version: "3.3"
services:
  postgres:
    image: postgres
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"